// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASEBnFncMGESigX9FEf_AcetTuhd6lmHc',
    appId: '1:489611616436:web:b035dc913dbc4a8bd2f7e1',
    messagingSenderId: '489611616436',
    projectId: 'ukm-app-94480',
    authDomain: 'ukm-app-94480.firebaseapp.com',
    storageBucket: 'ukm-app-94480.firebasestorage.app',
    measurementId: 'G-XCB3BTZ1YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBNdxJkLsvqXdkmJwu8-_9x81TB7kHV4',
    appId: '1:489611616436:android:a5f69a506cd770c8d2f7e1',
    messagingSenderId: '489611616436',
    projectId: 'ukm-app-94480',
    storageBucket: 'ukm-app-94480.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5l1CG0nZWlTgbYJdllKCGAd5giItXic',
    appId: '1:489611616436:ios:3a74f55706fa692bd2f7e1',
    messagingSenderId: '489611616436',
    projectId: 'ukm-app-94480',
    storageBucket: 'ukm-app-94480.firebasestorage.app',
    iosBundleId: 'com.bryant.ukmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5l1CG0nZWlTgbYJdllKCGAd5giItXic',
    appId: '1:489611616436:ios:3a74f55706fa692bd2f7e1',
    messagingSenderId: '489611616436',
    projectId: 'ukm-app-94480',
    storageBucket: 'ukm-app-94480.firebasestorage.app',
    iosBundleId: 'com.bryant.ukmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASEBnFncMGESigX9FEf_AcetTuhd6lmHc',
    appId: '1:489611616436:web:5623d5c5f4a053bcd2f7e1',
    messagingSenderId: '489611616436',
    projectId: 'ukm-app-94480',
    authDomain: 'ukm-app-94480.firebaseapp.com',
    storageBucket: 'ukm-app-94480.firebasestorage.app',
    measurementId: 'G-DFJ7DXXLKC',
  );
}
